# runtime: python311
# threadsafe: true

# handlers:
# - url: /
#   script: main.app
runtime: python311
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
